language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sdchhoker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sdchhoker/react-test npm test

after_success:
  - docker build -t sdchhoker/multi-client ./client
  - docker build -t sdchhoker/multi-nginx ./nginx
  - docker build -t sdchhoker/multi-server ./server
  - docker build -t sdchhoker/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sdchhoker/multi-client
  - docker push sdchhoker/multi-nginx
  - docker push sdchhoker/multi-server
  - docker push sdchhoker/multi-worker
deploy:
  provider:  elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-230026605781
  bucket_path: docker_multi
  on:
    master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
