version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: "redis"
  api:
    image: "cosmtrek/air"
    working_dir: /go/src/github.com/sdchhoker/worker/server
    volumes:
      - ./server:/go/src/github.com/sdchhoker/worker/server
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    image: "cosmtrek/air"
    depends_on:
      - redis
    working_dir: /go/src/github.com/sdchhoker/worker/worker
    volumes:
    - ./worker:/go/src/github.com/sdchhoker/worker/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - "3050:80"
    depends_on:
      - api
      - client